# A YAML configuration file for the model analyze pipeline.
# General pipeline settings
ds_name: quickstart

# model field names
dm_name: yolov11
dm_eval_key: yolov11_eval

# label key field name
label_key_name: "bbox"

# plot configs
nbins: 80
step_value: 0.5

# pipline tasks
step: null
run_full_pipeline: false



# | `step`           | `run_full_pipeline`                       | Behavior                                      |
# | ---------------- | ----------------------------------------- | --------------------------------------------- |
# | `"plot_tp_area"` | `false`                                   | Starts from `plot_tp_area`                    |
# | `null`           | `true`                                    | Runs full pipeline                            |
# | `"full"`         | `false` *(if you added “full” as choice)* | Runs full pipeline                            |
# | `null`           | `false`                                   | Runs full pipeline *(new default behavior)* |


